nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: []
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
        hosts: []
        origin_regex: false
    paths:
        '^/api':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['GET', 'DELETE']
            max_age: 3600
        '^/auth':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['POST', 'PUT']
            max_age: 3600